/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/screens/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/screens/detalhes`; params?: Router.UnknownInputParams; } | { pathname: `/../app`; params?: Router.UnknownInputParams; } | { pathname: `/routes/index`; params?: Router.UnknownInputParams; } | { pathname: `/routes/bottom.routes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/input`; params?: Router.UnknownInputParams; } | { pathname: `/components/input/styles`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/inicio`; params?: Router.UnknownInputParams; } | { pathname: `/screens/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/screens/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/detalhes`; params?: Router.UnknownOutputParams; } | { pathname: `/../app`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/index`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/bottom.routes`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/input`; params?: Router.UnknownOutputParams; } | { pathname: `/components/input/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/use-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/use-theme-color`; params?: Router.UnknownOutputParams; } | { pathname: `/screens`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/inicio`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/screens/cadastro${`?${string}` | `#${string}` | ''}` | `/screens/home${`?${string}` | `#${string}` | ''}` | `/screens/perfil${`?${string}` | `#${string}` | ''}` | `/screens/detalhes${`?${string}` | `#${string}` | ''}` | `/../app${`?${string}` | `#${string}` | ''}` | `/routes/index${`?${string}` | `#${string}` | ''}` | `/routes/bottom.routes${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/input${`?${string}` | `#${string}` | ''}` | `/components/input/styles${`?${string}` | `#${string}` | ''}` | `/constants/theme${`?${string}` | `#${string}` | ''}` | `/hooks/use-color-scheme${`?${string}` | `#${string}` | ''}` | `/hooks/use-theme-color${`?${string}` | `#${string}` | ''}` | `/screens${`?${string}` | `#${string}` | ''}` | `/screens/inicio${`?${string}` | `#${string}` | ''}` | `/screens/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/screens/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/screens/detalhes`; params?: Router.UnknownInputParams; } | { pathname: `/../app`; params?: Router.UnknownInputParams; } | { pathname: `/routes/index`; params?: Router.UnknownInputParams; } | { pathname: `/routes/bottom.routes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/input`; params?: Router.UnknownInputParams; } | { pathname: `/components/input/styles`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/inicio`; params?: Router.UnknownInputParams; } | { pathname: `/screens/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
